# Generated by Django 4.1.2 on 2022-11-04 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(default=11),
            preserve_default=False,
        ),
    ]
